require('dotenv').config();

module.exports = {
  user: process.env.USER,
  password: process.env.PASSWORD,

  MONGO_URL : process.env.MONGO_URL,
  MONGO_DB_NAME : process.env.MONGO_DB_NAME,
  MONGO_LOG_COLLECTION : process.env.MONGO_LOG_COLLECTION,
  MONGO_COLLECTION_BUSQUEDAS : process.env.MONGO_COLLECTION_BUSQUEDAS,
  MONGO_COLLECTION_GRUPOS : process.env.MONGO_COLLECTION_GRUPOS,
  MONGO_COLLECTION_PARAMETROS : process.env.MONGO_COLLECTION_PARAMETROS,

  TOKEN_SERVICE: process.env.TOKEN_SERVICE,
  TOKEN_SECRET: process.env.TOKEN_SECRET,

  INTEGRATION_URI: process.env.INTEGRATION_URI,
  LOCHTEL_NAME: process.env.LOCHTEL_NAME,
  LOCHTEL_USER: process.env.LOCHTEL_USER,
  LOCHTEL_PASSWORD: process.env.LOCHTEL_PASSWORD,
  LOCHTEL_ORIGEN_TRANSACCION: process.env.LOCHTEL_ORIGEN_TRANSACCION,
  MONGO_COLLECTION_LOCHTEL: process.env.MONGO_COLLECTION_LOCHTEL,
  MONGO_COLLECTION_PAGOS_LOCHTEL: process.env.MONGO_COLLECTION_PAGOS_LOCHTEL,

  MONGODB_URL: process.env.MONGODB_URL,

  SEMAPA_NAME: process.env.SEMAPA_NAME,
};
